#! /bin/bash

bspc config border_width        	2
bspc config window_gap          	0

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config external_rules_command  ~/.config/bspwm/get-split-direction.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

. ~/.config/bspwm/profile

sxhkd &
~/.config/bspwm/panel &

trayer --edge top \
	   --align right \
	   --widthtype request \
	   --expand true \
	   --SetDockType true \
	   --SetPartialStrut true \
	   --transparent true \
	   --alpha 0 \
	   --tint 0x000000 \
	   --expand true \
	   --heighttype pixel \
	   --height 23 \
	   --padding 1 &
feh --bg-scale ~/dotfiles/look/Wallpapers/solid-000000-1920x1080.jpg &
~/bin/gifbg.sh ~/dotfiles/look/Wallpapers/beesnbombs-worms.gif &
telegram-desktop &
deluge &
cbatticon &
nm-applet &
xset b off &
unclutter -idle 2 &
