#! /bin/bash

bspc config top_padding $BSPWM_PANEL_HEIGHT

[[ -e "$BSPWM_PANEL_FIFO"  ]] || mkfifo "$BSPWM_PANEL_FIFO"
[[ -e "$BSPWM_VOLUME_FIFO" ]] || mkfifo "$BSPWM_VOLUME_FIFO"

bspc subscribe report > "$BSPWM_PANEL_FIFO" &

~/.config/bspwm/panel_xmobar < "$BSPWM_PANEL_FIFO" | xmobar 
