#! /bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
VOLUME_FIFO=/tmp/.volume-pipe 

bspc config top_padding $PANEL_HEIGHT

[[ -e "$PANEL_FIFO"  ]] || mkfifo "$PANEL_FIFO"
[[ -e "$VOLUME_FIFO" ]] || mkfifo "$VOLUME_FIFO"

bspc subscribe report > "$PANEL_FIFO" &

/home/ovaube/.config/bspwm/panel_xmobar < "$PANEL_FIFO" | xmobar 
